### ISSUE TITLE
Increase clickable region for icons on mobile

### ISSUE THREAD

**Issue by msrichardson** [conveyal/trimet-mod-otp#111]
Can sometimes be frustrating trying to click on a stop/car2go/etc icon to pull up the "bubble".  As such, please increase the clickable region.

TriMet has used a 20x20 pixel image canvas, partially as it provides a decent sized clickable region. 

![croppercapture 299](https://user-images.githubusercontent.com/4853348/46487933-1ed43880-c7b6-11e8-9700-f9d870288d71.png)

**Comment by msrichardson** [comment]
@landonreed Looks like the icon size increased, in addition the canvas size.

![croppercapture 305](https://user-images.githubusercontent.com/4853348/46562873-2b8a8680-c8b3-11e8-901a-648b513800c5.png)

**Comment by fpurcell** [comment]
> the actual size match the clickable region seems in line with a user's expectations

My usability research for https://maps.trimet.org/m.html (map of real-time vehicle locations created about 7 years ago for on-street employees) tells me that yes it can be _slightly_ frustrating when you click one item and instead the popup for its neighbor is opened.  But it's far less frustrating than either not being able to open a popup because the click area is too small, or having icons overlap each other because the image is so big.  I really think having 11x11 stop icon image centered on a 20x20 transparent image canvas is the best solution (actually, a 20x20 canvas might be a little small -- the mobile vehicles icons are 32x32 sized canvases -- but let's start with 20x20 and see how it works). We've been doing the larger canvas trick on our maps for many years now, and I can't recall a single customer complaint.

**Comment by landonreed** [comment]
This still seems a bit strange to me, since the problem of overlapping icons can be mitigated by the user just zooming in further, but I have a fix in https://github.com/opentripplanner/otp-react-redux/commit/2cff6483f9c9d771a0ebb0a14adf0973ce4a56fa (yet to be deployed).  I think it might be worth updating the usability research because it's a few years old and users' expectations might have shifted over that time. In general, I feel like icons overlaid on maps have increased in size, but I'm having trouble thinking of other cases/applications where I have encountered this kind of oversized, invisible clickable area.

**Comment by fpurcell** [comment]
Hey @landonreed ... if there's another solution to the 2 identified problems (icons are frustratingly small to click; increasing the icon image to 20x20 makes the map too cluttered), I'm all for it.  The solution I offer (small image on 20x20 canvas) is one that has worked for us in the past.  But certainly not married to it, if there's another solution which addresses both identified problems.

**Comment by msrichardson** [comment]
We're on-board with the latest fix.  Thanks!
