### ISSUE TITLE
Mobile: Selecting destination from map bug

### ISSUE THREAD

**Issue by msrichardson** [conveyal/trimet-mod-otp#146]
(or at least presume this is a bug)

On mobile, if the user selects their destination from the map, the destination field will display the selected destination, but then the app stays on the initial page - it doesn't move on to ask from where you are starting.  User must also select the starting point from the map to get to the next screen.

**Comment by demory** [comment]
@msrichardson I am only able to recreate this when I block the application's access to the current location. When the current location is auto-detected as the origin and the destination is selected via map click, it takes me to the next screen as expected. (Let me know if that is not your experience as well.)

Currently, the app only advances to the 2nd screen if both an origin and destination are defined. So in the case where a mobile user blocks auto-detection of the current location (which we assumed to be rare), then yes, they are expected to select both on the first screen. 

Let us know if you'd like us to change it so that, in the case of blocked location auto-detection, the app advances to the second screen after a single location is entered. In this case, the second screen will initially show one empty location field, and the "Plan Trip" button will be disabled until the user specifies the second location.

**Comment by msrichardson** [comment]
Ah, that makes sense.  I've been purposely testing without allowing current location.  I will find out if we want that changed or not.  Thanks.

**Comment by msrichardson** [comment]
@demory We'd like it to be changed as you describe in the last paragraph above.  Thank you!
