### ISSUE TITLE
Unnecessary BIKETOWN Transfer

### ISSUE THREAD

**Issue by msrichardson** [conveyal/trimet-mod-otp#159]
The following itinerary, using transit+BIKETOWN, includes an unnecessary BIKETOWN tranfers.  It appears that you drop off then pick-up the same bike. 

https://trimet-mod-dev.conveyal.com/#/?ui_activeItinerary=0&fromPlace=2025%20SE%2022nd%20Ave%2C%20Portland%2C%20OR%2C%20USA%3A%3A45.508042%2C-122.643481&toPlace=4311%20SE%2037th%20Ave%2C%20Portland%2C%20OR%2C%20USA%3A%3A45.491624%2C-122.625601&date=2019-02-21&time=14%3A41&arriveBy=false&mode=BUS%2CTRAM%2CRAIL%2CGONDOLA%2CBICYCLE_RENT&showIntermediateStops=true&maxWalkDistance=4828&maxBikeDistance=4828&optimize=SAFE&bikeSpeed=3.58&ignoreRealtimeUpdates=true&companies=

![image1](https://user-images.githubusercontent.com/4853348/53206887-03dc5680-35e7-11e9-8880-a9550c519852.png)

**Comment by evansiroky** [comment]
This seems to be an issue with the underlying bicycle routing data in OTP as this issue is reproducible without bikeshare enabled. The underlying OSM data appears to be ok.

<img width="1329" alt="screen shot 2019-02-22 at 9 32 00 am" src="https://user-images.githubusercontent.com/3112493/53259770-ccbc8280-3684-11e9-91ff-9960bc6ef157.png">

**Comment by msrichardson** [comment]
Issue turned out to be related to turn restrictions in OSM, which have been resolved.
