### ISSUE TITLE
Daylight Saving Time

### ISSUE THREAD

**Issue by msrichardson** [conveyal/trimet-mod-otp#162]
There appears to be a bug related to daylight saving time.  If a trip is planned after approximately 2 AM on March 10 (when DST goes into effect) or later, trips show an hour off from the requested depart or arrive by time.  See example trip below.

https://modbeta.trimet.org/map/#/?fromPlace=Portland%20Int%27l%20Airport%20MAX%20Station%20%28TriMet%20Stop%20ID%2010579%29%3A%3A45.587584%2C-122.5931&toPlace=SE%2052nd%20%26%20Division%20%28TriMet%20Stop%20ID%207679%29%2C%20Portland%3A%3A45.505034%2C-122.609081&date=2019-03-10&time=15%3A00&arriveBy=false&mode=WALK%2CBUS%2CTRAM%2CRAIL%2CGONDOLA&showIntermediateStops=true&maxWalkDistance=1207&optimize=QUICK&walkSpeed=1.34&ignoreRealtimeUpdates=true&companies=&ui_activeItinerary=0

**Comment by fpurcell** [comment]
A couple of notes:
  a) This appears to be a UI problem, since the same trip with the old interface, against the same graph, is not showing these problems: https://maps.trimet.org/ui_mod/
  b) This is what ride is showing for March 10th https://ride.trimet.org?submit&fromPlace=PDX::45.589180,-122.593460&toPlace=SE%2052nd%20@%20Division::45.505035,-122.609085&mode=TRANSIT,WALK&min=QUICK&maxWalkDistance=1260&time=3:00pm&date=3/10/2019
  c) And what ride shows when using the MOD graph: https://ride.trimet.org/?purl=/otp_mod/plan&submit&fromPlace=PDX::45.589180,-122.593460&toPlace=SE%2052nd%20@%20Division::45.505035,-122.609085&mode=TRANSIT,WALK&min=QUICK&maxWalkDistance=1260&time=3:00pm&date=3/10/2019

**Comment by fpurcell** [comment]
p.s., I suggest adding a 'purl' url parameter, which one can point the UI at a different graph instance; it's a handy tool in these situations.  (And I think I saw mention of adding such a url to the MOD map somewhere else before).
