### ISSUE TITLE
Permission to use GPS on load

### ISSUE THREAD

**Issue by fpurcell** [conveyal/trimet-mod-otp#20]
Can't have the location permission prompt on load.  (Esp on desktop, where gps might not be available nor relevant).

![gps](https://user-images.githubusercontent.com/64323/31035865-7e606e1a-a51e-11e7-8fd9-2a5823e6b0ea.png)

**Comment by demory** [comment]
We will change it so that in desktop mode, the location prompt will not be shown until user specifically set "current location" as endpoint.

In mobile mode, we need the location at load time to show in the initial screen. Changing this would mean changing the overall ux flow for the mobile version.
