### ISSUE TITLE
BUG: resizing browser window breaks map and from & to forms (on Mac browsers)

### ISSUE THREAD

**Issue by fpurcell** [conveyal/trimet-mod-otp#32]
On Firefox, Chrome and Opera on my MacBook, I'm seeing resize problems.   

1. Original view:
![original view](https://user-images.githubusercontent.com/64323/31257592-3b659f7a-a9ee-11e7-9905-c7a2cf37ba23.png)

2. Resize to smaller view ... goes mobile after playing around:
![smaller map](https://user-images.githubusercontent.com/64323/31257603-4b81df72-a9ee-11e7-81a1-198b3755e342.png)

3. Resize browser again ... now map is gone and forms don't work ... note also that TriMet logo on top menu is gone:
![resize browser map gone and forms broken](https://user-images.githubusercontent.com/64323/31257621-67317142-a9ee-11e7-92a6-2fb1679c325a.png)

**Comment by demory** [comment]
Issue with map breaking on window resize should be fixed by https://github.com/opentripplanner/otp-react-redux/commit/cd28195f2cb4bac7f1a8fa785430145b6ecdd6f8

For the form, we no longer switch to mobile mode when a desktop window is scaled down. (Mobile mode is now detected by the browser+OS rather than window size.) At low sizes in desktop mode the map will go away but the main search/results form should continue to work.

**Comment by fpurcell** [comment]
Fixed

**Comment by fpurcell** [comment]
seems fixed . june 2018
