### ISSUE TITLE
UI: date and/or time form need to be checked

### ISSUE THREAD

**Issue by fpurcell** [conveyal/trimet-mod-otp#48]
Via the UI, one can empty out the date and time fields, and then submit a trip. Having a non-valid date is problematic, as the map app will submit requests to OTP with an empty &date=& parameter, which then causes an error.  

![screen shot 2018-01-11 at 11 54 12 pm](https://user-images.githubusercontent.com/64323/34865074-194e41d6-f72c-11e7-8c3d-43de8ce58c94.png)

Best solution would the following:
  if the date form has bogus data, then don't send either &time=&date= parameters
  if the time form is blank, I think OTP works okay with just a date, so no need to do anything special

BTW, there might be a bug in OTP: this URL returns a "java.lang.NullPointerException null": https://trimet-otp.conveyal.com/otp/routers/default/plan?fromPlace=45.5252843095301%2C-122.68014192581178&toPlace=45.52812549856162%2C-122.67655849456789&date=&time=&arriveBy=false&mode=TRAM%2CBUS%2CGONDOLA%2CWALK%2CBICYCLE%2CBICYCLE_RENT&showIntermediateStops=true&maxWalkDistance=402.3&optimize=QUICK&walkSpeed=1.34&bikeSpeed=3.58&ignoreRealtimeUpdates=true

**Comment by msrichardson** [comment]
Related to this, on the desktop version, the time display is currently uses a 24-hr format, rather than a 12-hr format.  Even so, one can enter time in either format; however, if one enters a time without minutes in either format (ex: 4 PM or 16), it will result in a trip plan at a totally different time of day.

4 PM without minutes - trip for after 11 PM:
![croppercapture 224](https://user-images.githubusercontent.com/4853348/35891966-ca39fb5a-0b5b-11e8-840b-cadbe54a9daa.png)

4 PM with minutes - trip at expected time:
![croppercapture 225](https://user-images.githubusercontent.com/4853348/35891968-d492816c-0b5b-11e8-910d-11121d15d279.png)

1600 hrs without the minutes - trip after 1 AM
![croppercapture 226](https://user-images.githubusercontent.com/4853348/35891985-ec5ecbb6-0b5b-11e8-8f80-72a7bdddedad.png)

1600 hrs with the minutes - trip at expected time:
![croppercapture 227](https://user-images.githubusercontent.com/4853348/35892042-52078e80-0b5c-11e8-9c79-5ae44523ad7e.png)

**Comment by demory** [comment]
Addressed in https://github.com/opentripplanner/otp-react-redux/commit/e6b3a85d9153fd1dbd241c64e113b707c8da4492

If either the date or time as entered is invalid, they will not be included in the request and OTP will use the default (current) time.

**Comment by fpurcell** [comment]
Closing
