### ISSUE TITLE
Print and custom URL path...

### ISSUE THREAD

**Issue by fpurcell** [conveyal/trimet-mod-otp#91]
Here's a trip plan on the 'map' instance here at TriMet:
https://modbeta.trimet.org/map?fromPlace=45.526314%2C-122.6762832&toPlace=45.512121%2C-122.6531

But printing isn't working (probably due to the custom path): 
https://modbeta.trimet.org/map/print?fromPlace=45.526314%2C-122.6762832&toPlace=45.512121%2C-122.6531

**Comment by demory** [comment]
@fpurcell I think this may be a server configuration issue. Getting react-router to play well with various web servers, especially when subdirectories or custom paths are involved, can be tricky.

I was able (after a good bit of hair pulling) to get `/print` to work from a subdirectory on the test server (which is running nginx) by tweaking the nginx config. What server software are you using here?

**Comment by fpurcell** [comment]
It is just Apache, serving static content from the htdocs directory.  Node isn't installed ... it's just taking the 3 artifacts from the yarn build step, and slapping them up on that server under the '/map' directory.

BTW, I'm going to try to do the same locally, by serving up the MOD static content in /map with this simple http server:  python -m SimpleHTTPServer 80.   (I'll report back at today's meeting).

**Comment by fpurcell** [comment]
Hey David,

Here's a simple example of how to see the issues with having the 'print' not sitting under the path defined via reactRouter:
 
  1. clone trimet-mod-otp
  1. cd trimet-mod-otp
  1. edit lib/config.yml by adding:
    reactRouter:
      basename: dist
  1. yarn install; yarn build
  1. python -m SimpleHTTPServer 80
  1. visit http://localhost/dist/ in a browser, and plan a trip...
  1. now click the print button ... things don't work 
  1. the output from the simple server:
127.0.0.1 - - [18/Sep/2018 16:55:46] code 404, message File not found
127.0.0.1 - - [18/Sep/2018 16:55:46] "GET /dist/print?fromPlace=45.5259532796522%2C-122.6827523520081&toPlace=45.50714134%2C-122.65673282&date=2018-09-18&time=16%3A45&arriveBy=false&mode=WALK%2CBUS%2CTRAM%2CRAIL%2CGONDOLA&showIntermediateStops=true&maxWalkDistance=1207&optimize=QUICK&walkSpeed=1.34&ignoreRealtimeUpdates=true&companies= HTTP/1.1" 404 -

**Comment by landonreed** [comment]
The root problem here seems to be that the server is not configured to default to `index.html` when a file is not found at the path. This is required behavior for single-page applications, which are designed to return `index.html` for pretty much every route.

If you install [SimpleHTTP404Server](https://pypi.org/project/SimpleHTTP404Server/) and replace step 5 with the following steps you should get the desired result:

- `cp index.html 404.html`
- `python -m SimpleHTTP404Server 80`

As for how we might fix the TriMet server, [this post](https://medium.com/@pshrmn/single-page-applications-and-the-server-32a23d67936) has instructions on using a Rewrite Rule (reproduced below) to serve `index.html` for files not found:

```
RewriteEngine On
# set the base URL prefix
RewriteBase /
# for requests for index.html, just respond with the file
RewriteRule ^index\.html$ - [L]
# if requested path is not a valid filename, continue rewrite
RewriteCond %{REQUEST_FILENAME} !-f
# if requested path is not a valid directory, continue rewrite
RewriteCond %{REQUEST_FILENAME} !-d
# if you have continue to here, respond with index.html
RewriteRule . /index.html [L]
```

**Comment by landonreed** [comment]
@demory just reminded me that another solution would be to modify the react-router to use hash routing, so the print URL would like `https://modbeta.trimet.org/map#print?fromPlace=45.526314%2C-122.6762832&toPlace=45.512121%2C-122.6531`.

**Comment by fpurcell** [comment]
Hey @landonreed 

I think you're on to something with the /map#print and reactRouter, since the current path happening now on https://modbeta.trimet.org/map is the issue. 

That server (as well the simple python server in my example above) do find index.html when not on the URL.  The issue isn't the app path ... that app renders on those URLs w/out specifying indext.html.  Rather, it's the print path that is messed up.

Take care and here to test any fixes on this end (using the python simple http server is also a good way to test the print path).

**Comment by landonreed** [comment]
So, the app will indeed render if you're at the root path (i.e., `/map` or `/dist` in your example above.  This is because the `index.html` file is found and returned.  But when a sub-directory is included in the path `/map/print` the server attempts to look for a directory called `print` inside the directory it's serving out of.

To demonstrate this, you can use the same instructions you originally posted, but do `mkdir dist/print; cp dist/index.html dist/print/` before starting up `SimpleHTTPServer`.  

So, I guess this would be another solution to the original problem (although a bit hacky).

**Comment by fpurcell** [comment]
Hey Landon,  Hacky is sometimes good (story of my life).  I see what you mean with : mkdir dist/print/; cd dist/print; ln -s ../*.* .; I tried this and it works, and the print screen does render. It's something we could do as a temp workaround (or even a last resort) to getting print working. But I'm hoping there's a better solution out there, ala the #print routing, etc...  Talked with my colleague John (who might chime in), and the server config options are a non-starter...

**Comment by johnzimm** [comment]
Chiming in to maybe further clarify what we are trying to accomplish.

Essentially we want the single page web application to run completely out of a a configurable context.  All of the resources and self reference routes/links should be generated completely within that context during build time.  A configurable context allows us to use the domain/subdomain for multiple web applications (single page apps or otherwise) without paths colliding.  Dedicating a domain/subdomain to a single page application would then be an option and not a requirement.  Relying on symlinks and/or url rewriting is horribly error prone and overly complicates any other use of the domain/subdomain and really isn't a path we want to entertain.

In React Router the parameter to modify the "context" I am eyeballing (not a React developer myself) is the basename.  Kind of like here: https://medium.com/@svinkle/how-to-deploy-a-react-app-to-a-subdirectory-f694d46427c1.  I'm not sure how this maps to webpack, but probably the "publicPath" parameter?

For our electronic fare project we have a similar strategy employed in an angular application.

- https://myhopcard.com/home/#/account
- https://myhopcard.com/programs/#/someotherroute

"home" and "programs" in the urls above represent the contexts (or basename) of two different single page applications hosted on the same domain.  Everything they need to self reference is available in their respective context independently.

Using modbeta.trimet.org as example we might want two different builds or versions of a map deployed at two different contexts like....

 - https://modbeta.trimet.org/map
   could be one build/deployment of trimet-mod-otp
 - https://modbeta.trimet.org/anothermap
   would be a completely separate build/deployment of trimet-mod-otp

Or at trimet.org the following would be completely separate applications.....

 - https://trimet.org/map
 - https://trimet.org/transittracker

And none of the routes or requirements for those deployments would overlap.  At trimet.org especially we have several applications that will be replaced that currently do not play well with others on the same domain. Going forward we've tried to make the ability for applications to run out of a context a requirement.

Being able to run the application out of context will allow us and anyone else looking to implement the application to reasonable deploy and integrate it more flexible and reasonably with existing deployments.

**Comment by landonreed** [comment]
Thanks for the note, @johnzimm. It sounds like using the hash routing `/map#print` is the way to go based on these requirements. And taking into account that the Hop Card site also uses hash routing, there is already precedent for this at TriMet.

**Comment by fpurcell** [comment]
This is resolved.  Much appreciated, folks!
